services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: PlexServer
    restart: unless-stopped
    environment:
      PLEX_UID: ${PUID:?}
      PLEX_GUI: ${PGUI:?}
      TZ: ${TZ:?}
      ADVERTISE_IP: ${ADVERTISE_IP:?}
      PLEX_CLAIM: ${PLEX_CLAIM}
    labels:
      - com.centurylinklabs.watchtower.enable=true
    init: true
    network_mode: bridge
    ports:
      # Plex Media Server
        - 32400:32400/tcp
      # Plex Companion
        # - 3005:3005/tcp
      # Roku via Plex companion
        # - 8324:8324/tcp
      # Plex DLNA Server
        # - 32469:32469/tcp
      # Plex DLNA Server
        # - 1900:1900/udp
      # Network discovery
        # - 32410:32410/udp
        # - 32412:32412/udp
        # - 32413:32413/udp
        # - 32414:32414/udp
    volumes:
      - ./config/plex:/config
      - /mnt/ramdisk:/transcode
      - /mnt/nas/movies:/data/movies
      - /mnt/nas/series:/data/series

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: plex-tautulli
    restart: unless-stopped
    environment:
      PLEX_UID: ${PUID:?}
      PLEX_GUI: ${PGUI:?}
      TZ: ${TZ:?}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.tautulli.entrypoints=https
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.tls.certresolver=cloudflare
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
      - traefik.http.routers.tautulli.middlewares=authentik@file
    networks:
      - traefik
    volumes:
      - ./config/tautulli:/config

networks:
  traefik:
    external: true